name: Generate build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for submodules

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to build branch
        uses: actions/checkout@v3
        with:
          ref: refs/heads/build # Check out the build branch
          fetch-depth: 0 # Fetch all history for submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Build: ${{ github.sha }} ${{ github.event.head_commit.message }}"
          git push -u origin build
