name: Generate build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for submodules

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create or checkout build branch
        run: |
          git fetch origin
          if git show-ref --quiet refs/heads/build; then
            git checkout build
          else
            git checkout -b build
          fi

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Build: ${{ github.sha }} ${{ github.event.head_commit.message }}" || echo "No changes to commit"
          git push origin build
